# frozen_string_literal: true

source "https://rubygems.org"

# Rails 7 requires Ruby 3.1+. Use rbenv, asdf, or Homebrew (see README).
ruby ">= 3.1.0"

gem "rails", "~> 7.2.0"
gem "pg", "~> 1.5"
gem "puma", ">= 5.0"
gem "redis", ">= 4.0"
gem "sidekiq", "~> 7.0"
gem "devise", "~> 4.9"
gem "sprockets-rails"
gem "jsbundling-rails"
gem "turbo-rails"
gem "jbuilder"
gem "bootsnap", require: false
gem "dotenv-rails", groups: [:development, :test]
gem "openai"

group :development, :test do
  gem "debug", platforms: :mri
  gem "minitest", "< 6"  # Rails 7.2 test runner expects Minitest 5 run(reporter, options) signature
end

group :development do
  gem "web-console"
  gem "foreman"
end
